version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network
      
  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "postgres"
  #   restart: always
  #   ports:
  #     - "16543:80"
  #   depends_on:
  #     - postgres-compose
  #   networks:
  #     - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge